/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
const sidebars = {
  // =============================================
  // LEARN - Unified educational content
  // =============================================
  learn: [
    {
      type: 'doc',
      id: 'learn/README',
      label: '📚 Learn Overview',
    },
    {
      type: 'category',
      label: '🌱 Start Here',
      link: {
        type: 'doc',
        id: 'learn/fundamentals/index',
      },
      items: [
        'learn/fundamentals/what-is-bitcoin',
        'learn/fundamentals/what-is-self-custody',
        'learn/fundamentals/holding-bitcoin',
        'learn/fundamentals/choosing-your-path',
        'learn/fundamentals/threat-models',
      ],
    },
    {
      type: 'category',
      label: '🔑 Keys & Seeds',
      link: {
        type: 'doc',
        id: 'learn/keys/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'learn/keys'},
      ],
    },
    {
      type: 'category',
      label: '👛 Wallets',
      link: {
        type: 'doc',
        id: 'learn/wallets/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'learn/wallets'},
      ],
    },
    {
      type: 'category',
      label: '💸 Transactions',
      link: {
        type: 'doc',
        id: 'learn/transactions/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'learn/transactions'},
      ],
    },
    {
      type: 'category',
      label: '🕵️ Privacy',
      link: {
        type: 'doc',
        id: 'learn/privacy/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'learn/privacy'},
      ],
    },
    {
      type: 'category',
      label: '🖥️ Nodes',
      link: {
        type: 'doc',
        id: 'learn/nodes/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'learn/nodes'},
      ],
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '🛠️ View All Guides',
      href: '/guides/',
    },
    {
      type: 'link',
      label: '📖 Glossary',
      href: '/docs/reference/glossary/',
    },
  ],

  // =============================================
  // GUIDES - Practical setup guides
  // =============================================
  
  // Wallet Setup
  walletSetup: [
    {
      type: 'autogenerated',
      dirName: 'wallet-setup',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],
  
  // Security
  security: [
    {
      type: 'autogenerated',
      dirName: 'security',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],
  
  // Advanced
  advanced: [
    {
      type: 'autogenerated',
      dirName: 'advanced',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],
  
  // Reference
  reference: [
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],

  // =============================================
  // INFRASTRUCTURE & FIRMWARE
  // =============================================
  
  // Bitcoin Node
  bitcoinNode: [
    {
      type: 'autogenerated',
      dirName: 'bitcoin-node',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],
  
  // Open-source firmware
  libreboot: [
    {
      type: 'autogenerated',
      dirName: 'libreboot',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],
  
  coreboot: [
    {
      type: 'autogenerated',
      dirName: 'coreboot',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],

  // =============================================
  // PROJECTS
  // =============================================
  
  nostrSigningDevice: [
    {
      type: 'autogenerated',
      dirName: 'nostr-signing-device',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],

  seedSigner: [
    {
      type: 'autogenerated',
      dirName: 'seedsigner',
    },
    {
      type: 'html',
      value: '<hr style="margin: 16px 0; border-color: rgba(245, 158, 11, 0.3);">',
    },
    {
      type: 'link',
      label: '📚 Learn the Basics',
      href: '/docs/learn/',
    },
  ],
};

export default sidebars;