/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialBasics: [{type: 'autogenerated', dirName: 'basics'}],
  tutorialLibreboot: [{type: 'autogenerated', dirName: 'libreboot'}],
  tutorialSeed: [{type: 'autogenerated', dirName: 'seed'}],
  tutorialPassphrase: [{type: 'autogenerated', dirName: 'passphrase'}],
  tutorialAirgappedComputer: [{type: 'autogenerated', dirName: 'agc'}],
  tutorialBitcoinComputer: [{type: 'autogenerated', dirName: 'btccomputer'}],
  tutorialBitcoinNode: [{type: 'autogenerated', dirName: 'node'}],
  tutorialNostrSigningDevice: [{type: 'autogenerated', dirName: 'nsd'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['my-research/create-a-document'],
    },
  ],
   */
};

export default sidebars;
